package at.ac.tuwien.mogda.willgraph.entity;

import lombok.Builder;
import lombok.Data;
import org.springframework.data.geo.Point;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;
import org.springframework.data.neo4j.core.schema.Relationship;
import org.springframework.data.neo4j.core.support.UUIDStringGenerator;

import java.util.List;

import static org.springframework.data.neo4j.core.schema.Relationship.Direction.OUTGOING;

@Node("PointOfInterest")
@Data
@Builder
public class PointOfInterestEntity {
    //TODO: This currently uses the internal ID of Neo4j which is not so good for immutable entities
    // (SDN needs a way to set the field with the value generated by the database)
    // -> Search for good business key (ID)
    @Id
    @GeneratedValue(generatorClass = UUIDStringGenerator.class)
    private String id;
    private String name;
    private Integer score;
    //TODO: Check if needed or already covered with Address? ->Probably fine like this because better for performance?
    private Point location; // (lat, lon)

    @Relationship(type = "HAS_ADDRESS", direction = OUTGOING)
    private AddressEntity address;
    @Relationship(type = "IS_TYPE", direction = OUTGOING)
    private AmenityTypeEntity type;

    @Relationship(type = "CLOSE_TO_STATION", direction = OUTGOING)
    private List<TransportConnection> nearbyStations;

}
